//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadParcial2Mevy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serie
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string sinopsis { get; set; }
        public string director { get; set; }
        public Nullable<int> episodios { get; set; }
        public Nullable<System.DateTime> fecha_estreno { get; set; }
        public Nullable<short> estado { get; set; }
    }
}
